Add a chapter on syntax rewriting using the Dotty compiler
scalacenter/scala-3-migration-guide pull request #47
Opened 2020-09-04 14:59 UTC by eloots

This adds a section on syntax rewriting of source code by the Dotty compiler

2020-09-07 09:12 UTC, adpi2 requested changes

2020-09-07 09:12 UTC, adpi2 commented on docs/dotty-syntax-rewrites.md
> +variants may result in differences when going full circle.
In the Incompatibtility table page I have used the Blockquote syntax `>` to make a note box that is floating inside the text. It is like a tips and tricks box. ([result](https://scalacenter.github.io/scala-3-migration-guide/docs/incompatibility-table.html#scala-213-deprecations-and-feature-warnings)) ([source](https://github.com/scalacenter/scala-3-migration-guide/blob/master/docs/incompatibility-table.md#scala-213-deprecations-and-feature-warnings))

How about using the same layout for these two paragraphs. The first one could be floating inside the **Rewrite to SIB syntax** section. The second one could be floating inside the **Moving back to classic syntax**

What do you think?

2020-09-17 07:07 UTC, eloots commented on docs/dotty-syntax-rewrites.md
> +variants may result in differences when going full circle.
Good idea: I'll update this accordingly.
BTW; when I read your comments in the review the first time (almost 10 days ago), I think you made a comment about adding an sample invocation of `dotc` as an example. I don't see this comment anymore. Was it removed or am I dreaming?

2020-09-17 07:08 UTC, adpi2 approved these changes
Thank you for this good piece of writing!

2020-09-17 07:17 UTC, adpi2 commented on docs/dotty-syntax-rewrites.md
> +variants may result in differences when going full circle.
I have no recollection of such a comment :smile: 
I said on the slack channel that I like that you show the `dotc -help` output and so I did the same on the [Dotty migration mode page](https://scalacenter.github.io/scala-3-migration-guide/docs/dotty-rewrites.html)

2020-09-17 07:31 UTC, merged